[[redirects]]
  from = "https://melanieseltzer.netlify.com/*"
  to = "https://www.melanieseltzer.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://melanieseltzer.netlify.com/*"
  to = "http://www.melanieseltzer.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.melanieseltzer.io/*"
  to = "https://www.melanieseltzer.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://melanieseltzer.io/*"
  to = "https://www.melanieseltzer.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://melanieseltzer.io/*"
  to = "https://www.melanieseltzer.io/:splat"
  status = 301
  force = true